Build system updates. 	Use pkg-config to find ncurses and its required libs and cflags. 	Support DESTDIR. 	Support installdirs target. 	Support make overriding CFLAGS and LDFLAGS.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,46 +3,46 @@
 # Project Configuration						     #
 ######################################################################
 
-PKG_NAME="tiedit"
-PKG_VERSTR="v0.1"
-PKG_BUGREPORT="Mike Sharov <msharov@users.sourceforge.net>"
+pkg_name="tiedit"
+pkg_verstr="v0.1"
+pkg_bugreport="Mike Sharov <msharov@users.sourceforge.net>"
 
 # Files that get created by this script
-FILES="Config.mk config.h"
+files="Config.mk config.h"
 
 # Package options
-COMPONENTS='
+components='
 {
 name=[with-debug]
 desc=[	Compile for debugging]
-seds=[s/^#\(DEBUG\)/\1/]
+seds=[s/^#\(debug\)/\1/]
 }{
 name=[with-native]
 desc=[	Use -march=native]
 seds=[s/ -std=c/ -march=native -std=c/]
 }';
 
-# Libraries
-LIBS="ncurses"
-
 # First pair is used if nothing matches
-PROGS="CC=gcc CC=clang INSTALL=install"
+progs="CC=gcc CC=clang CC=cc INSTALL=install"
+
+# Required dependencies
+pkgs="ncurses"
 
 # Automatic vars
-[ -d .git ] && PKG_VERSTR=`git describe --always`
-PKG_MAJOR=`expr "$PKG_VERSTR" : 'v\([0-9]*\)\.[0-9]*'`
-PKG_MINOR=`expr "$PKG_VERSTR" : 'v[0-9]*\.\([0-9]*\)'`
-PKG_STRING="$PKG_NAME $PKG_VERSTR"
+[ -d .git ] && pkg_verstr=`git describe --always`
+pkg_major=`expr "$pkg_verstr" : 'v\([0-9]*\)\.[0-9]*'`
+pkg_minor=`expr "$pkg_verstr" : 'v[0-9]*\.\([0-9]*\)'`
+pkg_string="$pkg_name $pkg_verstr"
 
 # Miscellaneous substitutions
-CUSTSUBS="s/@PKG_NAME@/$PKG_NAME/g
-s/@PKG_VERSION@/"0x$PKG_MAJOR${PKG_MINOR}"/g
-s/@PKG_VERSTR@/$PKG_VERSTR/g
-s/@PKG_STRING@/$PKG_STRING/g
-s/@PKG_UNAME@/`echo $PKG_NAME|tr a-z A-Z`/g
-s/@PKG_BUGREPORT@/$PKG_BUGREPORT/g
-s/@PKG_MAJOR@/$PKG_MAJOR/g
-s/@PKG_MINOR@/$PKG_MINOR/g"
+custsubs="s/@pkg_name@/$pkg_name/g
+s/@pkg_version@/0x$pkg_major$pkg_minor/g
+s/@pkg_verstr@/$pkg_verstr/g
+s/@pkg_string@/$pkg_string/g
+s/@pkg_uname@/`echo $pkg_name|tr a-z A-Z`/g
+s/@pkg_bugreport@/$pkg_bugreport/g
+s/@pkg_major@/$pkg_major/g
+s/@pkg_minor@/$pkg_minor/g"
 
 ######################################################################
 #### The rest of the file is configuration code. Leave it alone. #####
@@ -52,25 +52,11 @@ die() { rm -f config.sed; exit; }
 sub() { printf "%s\n" "$1">>config.sed; }
 escpath() { echo $1 | sed 's/\//\\\//g'; }
 
-#### Set host-dependent options ######################################
-
-SYSNAME=`uname|tr A-Z a-z`
-case "$SYSNAME" in
-    *solaris*| *sun*)	SYSNAME="sun";;
-    *darwin*| *osx*)	SYSNAME="mac";;
-    *bsd*)		SYSNAME="bsd";;
-    *)			SYSNAME="linux";;
-esac
-
-if [ "$SYSNAME" != "linux" ]; then
-    sub "s/-p --ignore-fail-on-non-empty//"
-fi
-
 #### Printing helper functions #######################################
 
-PrintComponents() {
+print_components() {
     local cc name desc
-    cc=$COMPONENTS
+    cc=$components
     echo "Options:"
     while [ ! -z "$cc" ]; do
 	name=`expr "$cc" : '[^}]*name=\[\([^]]*\)\]'`
@@ -81,40 +67,38 @@ PrintComponents() {
     echo
 }
 
-PrintHelp() {
-    echo "This program configures $PKG_STRING to adapt to many kinds of systems.
+print_help() {
+    echo "This program configures $pkg_string build system.
 
-Usage: configure [OPTION]...
+Usage: configure [option]...
 
 Configuration:
   -h, --help		display this help and exit
   -V, --version		display version information and exit
 
 Installation directories:
-  --prefix=PREFIX	architecture-independent files [/usr/local]
-  --libdir=DIR		object code libraries [PREFIX/lib]
-  --includedir=DIR	C header files [PREFIX/include]
-  --mandir=DIR		man page directory [PREFIX/share/man]
-  --builddir=DIR	location for compiled objects [$TMPDIR/make]
+  --prefix=dir		architecture-independent root [/usr/local]
+  --bindir=dir		executable dir [prefix/bin]
+  --builddir=dir	location for compiled objects [\$TMPDIR/make]
 "
-    PrintComponents
-    echo "Report bugs to $PKG_BUGREPORT."
+    print_components
+    echo "Report bugs to $pkg_bugreport"
 }
 
-PrintVersion() {
-    echo "$PKG_NAME configure $PKG_VERSTR"
+print_version() {
+    echo "$pkg_name $pkg_verstr configure"
 }
 
-SubVar() {
+sub_var() {
     local esc2
     esc2=`escpath $2`
     eval ac_var_$1='$esc2';
     sub "s/@$1@/$esc2/g"
 }
 
-SubComp() {
+sub_comp() {
     local cc name seds
-    cc=$COMPONENTS
+    cc=$components
     while [ ! -z "$cc" ]; do
 	name=`expr "$cc" : '[^}]*name=\[\([^]]*\)\]'`
 	seds=`expr "$cc" : '[^}]*seds=\[\([^]]*\)\]'`
@@ -126,10 +110,10 @@ SubComp() {
 for i in $*; do
     case $i in
 	--)		break;;
-	--version |-V)	PrintVersion && die;;
-	--help |-h |-?)	PrintHelp && die;;
-	--*=*)		SubVar `expr "$i" : '--\([^=]*\)='` `expr "$i" : '[^=]*=\(.*\)'`;;
-	--*)		SubComp `expr "$i" : '--\(.*\)'`;;
+	--version |-V)	print_version && die;;
+	--help |-h |-?)	print_help && die;;
+	--*=*)		sub_var `expr -- "$i" : '--\([^=]*\)='` `expr -- "$i" : '[^=]*=\(.*\)'`;;
+	--*)		sub_comp `expr -- "$i" : '--\(.*\)'`;;
 	*)		echo "Error: unrecognized option \"$i\"" && die;;
     esac
 done
@@ -137,48 +121,18 @@ done
 #### Set directory prefixes ##########################################
 
 sub "s/@prefix@/${ac_var_prefix:=\/usr\/local}/g
-s/@bindir@/${ac_var_bindir:=$ac_var_prefix\/bin}/g
-s/@mandir@/${ac_var_mandir:=$ac_var_prefix\/share\/man}/g
-s/@includedir@/${ac_var_includedir:=$ac_var_prefix\/include}/g
-s/@libdir@/${ac_var_libdir:=$ac_var_prefix\/lib}/g
-s/@builddir@/$(escpath ${TMPDIR:-/tmp})\/make/g
-s/@pkgconfigdir@/${ac_var_pkgconfigdir:=$ac_var_libdir\/pkgconfig}/g"
+s/@bindir@/${ac_var_bindir:=\$\{prefix\}\/bin}/g
+s/@datadir@/${ac_var_datadir:=\$\{prefix\}\/share}/g
+s/@includedir@/${ac_var_includedir:=\$\{prefix\}\/include}/g
+s/@libdir@/${ac_var_libdir:=\$\{prefix\}\/lib}/g
+s/@TMPDIR@/$(escpath ${TMPDIR:-/tmp})/g
+s/@builddir@/\$\{TMPDIR\}\/make/g
+s/@pkgconfigdir@/${ac_var_pkgconfigdir:=\$\{libdir\}\/pkgconfig}/g"
 
-# Replace prefix variables, where available
-if [ "$ac_var_includedir" = "$ac_var_prefix\/include" ]; then
-    sub "s/$ac_var_includedir/\${prefix}\/include/";
-fi
-if [ "$ac_var_pkgconfigdir" = "$ac_var_libdir\/pkgconfig" ]; then
-    sub "s/$ac_var_pkgconfigdir/\${LIBDIR}\/pkgconfig/";
-fi
-if [ "$ac_var_libdir" = "$ac_var_prefix\/lib" ]; then
-    sub "s/$ac_var_libdir/\${prefix}\/lib/";
-fi
-if [ "$ac_var_bindir" = "$ac_var_prefix\/bin" ]; then
-    sub "s/$ac_var_bindir/\${prefix}\/bin/";
-fi
-if [ "$ac_var_mandir" = "$ac_var_prefix\/share\/man" ]; then
-    sub "s/$ac_var_mandir/\${prefix}\/share\/man/";
-fi
-if [ "$ac_var_libdir" = "\/usr\/local\/lib" -o "$ac_var_libdir" = "\/usr\/lib" ]; then
-    sub "s/ -L\${libdir}//";
-fi
-if [ "$ac_var_includedir" = "\/usr\/local\/include" -o "$ac_var_includedir" = "\/usr\/include" ]; then
-    sub "s/ -I\${includedir}//";
-fi
+#### Find headers, libs, programs, and subs ##########################
 
-#### Find libs, programs, and subs ###################################
-
-# Libraries are found using pkg-config
-for i in $LIBS; do
-    if pkg-config --exists $i; then
-	sub "s/@lib$i@/$(escpath "$(pkg-config --libs $i)")/;s/@inc$i@/$(escpath "$(pkg-config --cflags $i)")/";
-    else
-	sub "s/ @lib$i@//;s/ @inc$i@//";
-    fi
-done
 # Programs found using which
-for i in $PROGS; do
+for i in $progs; do
     pname=`expr "$i" : '\([^=]*\)=[^=]*'`
     pcall=`expr "$i" : '[^=]*=\([^=]*\)'`
     ppath=`eval echo \$\{$pname\}`
@@ -186,27 +140,41 @@ for i in $PROGS; do
     # First check if an environment variable is set
     [ ! -z "$ppath" ] && sub "s/@$pname@/$ppath/g"
     # Check if the program exists
-    [ -x `which $pcall 2>/dev/null` ] && sub "s/@$pname@/$pcall/g"
+    ppath=`which $pcall 2>/dev/null`
+    [ ! -z "$ppath" -a -x "$ppath" ] && sub "s/@$pname@/$pcall/g"
 done
-# If nothing found in first loop, set the first pair anyway.
-for i in $PROGS; do
+# If nothing found in first loop, set the first pair anyway
+for i in $progs; do
     pname=`expr "$i" : '\([^=]*\)=[^=]*'`
     pcall=`expr "$i" : '[^=]*=\([^=]*\)'`
     sub "s/@$pname@/$pcall/g"
 done
-# And, finally, the environment variables
-for i in $ENVIRONS; do
-    esciv="`eval echo '"'\$\{$i\}'"'|sed 's/\//\\\&/g'`"
-    ppath=`eval echo \$\{$pname\}`
-    ppath=`escpath "$ppath"`
-    [ ! -z "$ppath" ] && ppath=" $ppath"
-    sub "s/ @$i@/$ppath/g"
+
+# Packages found using pkg-config
+pkgconfig=`which pkg-config 2>/dev/null`
+if [ -z "$pkgconfig" -o ! -x "$pkgconfig" ]; then
+    echo "Error: could not find pkg-config"; die
+fi
+faildeps=""
+for i in $pkgs; do
+    `$pkgconfig --exists $i` || faildeps="$i $faildeps"
 done
-sub "$CUSTSUBS"
+if [ ! -z "$faildeps" ]; then
+    echo "Error: missing required packages: $faildeps"; die
+fi
+pkgcflags=$(escpath "$($pkgconfig --cflags $pkgs)")
+pkglibs=$(escpath "$($pkgconfig --libs-only-l $pkgs)")
+pkgldflags=$(escpath "$($pkgconfig --libs-only-L --libs-only-other $pkgs)")
+sub "s/@pkgcflags@/$pkgcflags/"
+sub "s/@pkglibs@/$pkglibs/"
+sub "s/@pkgldflags@/$pkgldflags/"
+
+# Miscellaneous custom substitutions
+sub "$custsubs"
 
 #### Apply substitutions to all files ################################
 
-for i in $FILES; do
+for i in $files; do
     sed -f config.sed $i.in > $i
 done
 
